### PR TITLE
#153740732 Embeded social content

### PR DESCRIPTION
**Pull request by proxiex**
### What does this PR do?
Embed social media content 

### Description of Task to be completed?
n/a
### How should this be manually tested?
[Launch app via Reaction commerce](https://elendil-rc-staging.herokuapp.com)
### What are the relevant pivotal tracker stories?
#[153740732](https://www.pivotaltracker.com/n/projects/2137293)

### Screenshots (if appropriate)
screen shot 2018-01-12 at 2 07 46 pm
screen shot 2018-01-12 at 2 07 34 pm

### CODE REVIEW

**Review by larrystone — APPROVED** [review]
All good

**Review by monsieurkayode — APPROVED** [review]
I love the page design, awesome

**Comment by chibuezeayogu** [comment]
Nice one.  Please check this `Launch app via Reaction commerce`. `Reaction commerce` is not a link and use appropriate header for  `What are the relevant pivotal tracker stories?`.

**Comment by andela-moe** [comment]
I believe you should raise this PR against `staging` and not `master`

**Pull request closed without merging**
